apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen
  argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app: gen
  template:
    metadata:
      labels:
        app: gen
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-claimer-yaml
      containers:
      - name: gen
        image: mado445555/pr3genjenkins:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/data_A"
          name: storage
        env:
        - name: PVC_A_PATH
          valueFrom:
            configMapKeyRef:
              name: gen-conf
              key: pvc_a
        - name: PVC_B_PATH
          valueFrom:
            configMapKeyRef:
              name: gen-conf
              key: pvc_b
        ports:
        - containerPort: 8080
