apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  argocd.argoproj.io/sync-wave: "0"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.237.134
    path: "/srv/nfs/pr3/myvolume"