apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claimer-yaml
  argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi